blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from blog import views
app_name = 'blog'
urlpatterns = [
    #url(r'^$',views.index, name='index'),
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    ]

custom_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('blog.urls',namespace='blog')),


]

blog/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    GENDER = (
    ('m', 'Male'),
    ('f', 'Female'),
    )
    gender = models.CharField(
    max_length=1,
        choices=GENDER,
        default='m',
    )
    pincode = models.IntegerField(validators=[MinValueValidator(100000),MaxValueValidator(999999)])
    email_id = models.EmailField(primary_key=True)
    def __str__(self):
        return self.user.username

class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('UserProfileInfo',on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("blog:post_detail",kwargs={'pk':self.pk})


    def __str__(self):
        return self.title



class Comment(models.Model):
    post = models.ForeignKey('blog.Post',on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("blog:post_list")

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from blog.models import UserProfileInfo
from django.contrib.auth.models import User
from .models import Post, Comment

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password')

class DateInput(forms.DateInput):
	input_type = 'date'

class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('first_name','last_name','gender','pincode','email_id')
         widgets = {
         	'dob': DateInput(),
         }

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('author','title', 'text',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

        widgets = {
            'author': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from blog.forms import UserForm,UserProfileInfoForm
from blog.models import Post, Comment
from django.utils import timezone
from blog.forms import PostForm, CommentForm
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


def index(request):
    #mydict={'insert_me':'This is from Views.py'}
    #return render(request,'myapp/index.html',context=mydict)
    return render(request,'blog/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    try:
        del request.session['username']
    except:
        pass
    return HttpResponseRedirect(reverse('blog:post_list'))



def register(request):
    registered = False
    if request.session.has_key('username'):
        username = request.session['username']
        return render(request,'blog/index.html')
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    if registered:
        return render(request,'blog/login.html')
    return render(request,'blog/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):
    if request.session.has_key('username'):
        username = request.session['username']
        return render(request,'blog/index.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                request.session['username'] = username
                #return HttpResponseRedirect(reverse('index'))
                return redirect('blog:post_list')
            else:
                return HttpResponse("Your account was inactive.")
        else:
            return HttpResponse("Invalid login details given.")
    else:
        return render(request, 'blog/login.html', {})


class AboutView(TemplateView):
    template_name = 'blog/about.html'

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post


class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/user_login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/user_login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/user_login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')


class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

#######################################
## Functions that require a pk match ##
#######################################

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)

blog/templates/blog/about.html
{% extends "base.html" %}
{% block content %}
<div class="ui main text container" >
    <div class="ui top  attached segment">
<h1>About me</h1>
<p>Thanks for visiting my blog! Check all this cool stuff about me!</p>

{% endblock %}

blog/templates/blog/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="ui main text container" >
    <div class="ui top  attached segment">
    <h1>New comment</h1>
    <form method="POST" class="ui form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="ui violet basic button">Post Comment</button>
    </form>
    </div>
</div>
    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcometo Blog World !</h1>
    {% if user.is_authenticated and user.is_superuser %}
    	<h2>Hello admin!
    {% elif user.is_authenticated %}
        <h2>Hello {{ user.username }}!</h2>
    {% else %}
        <h2>Register or Login if you'd like to!</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

blog/templates/blog/login.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="ui main text container">
      <div class="ui top  attached segment">
    	<div class="row">
        <div class="form-bg">
          <form method="post" class="ui form" action="{% url 'blog:user_login' %}">
            <h2>Login Page</h2>
            <br/>
            		{% csrf_token %}
            		{# A more "HTML" way of creating the login form#}
                <div class="form-group">
            		    <label for="username">Username:</label>
            		      <input type="text" name="username" placeholder="Username" id="uname">
                </div>
                <div class="form-group">
                  <label for="password">Password:</label>
            		    <input type="password" name="password" placeholder="Password">
                </div>
                <br/>
                <div class="align-center">
                <input type="submit" class="ui basic button" name="" value="Login">
                </div>
    			</form>

        </div>
        </div>
		</div>
  </div>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<div class="ui main text container" >
    <div class="ui top  attached segment">
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class='ui red basic button' type="submit" value="Confirm" />
  </form>
  </div>
  </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="ui main text container segment">
        <div class='ui huge header'>{{ post.title }}</div>
          <div class="top attached">
            <div class="item">
              {% if post.published_date %}
              <div class="content"><span><strong>
                {{ post.published_date }}</strong></span>
              </div>

              {% else %}

              {% endif %}
              <div class="btn">
              <div class='description'><p>{{ post.text|safe|linebreaksbr }}</p></div>
              </div>

              {% if user.is_authenticated %}
              <div class="btn">
              <a class="ui orange basic button" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
              <a class="ui red basic button" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove">Delete</span></a>
              {% if post.published_date %}
                {% else %}
              <a class="ui violet basic button"  href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
              {% endif %}

              </div>
              {% endif %}
              </div>
              </div>
              <div align="right">
                <a  class="ui violet basic button" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add comment</a>
              </div>

              <div class="container">


  {% for comment in post.comments.all %}
  <br>
      {% if user.is_authenticated or comment.approved_comment %}

              {{ comment.created_date }}


          <p>{{ comment.text|safe|linebreaks }}</p>
          <p>Posted by: <strong>{{ comment.author }}</strong></p>
          {% if not comment.approved_comment %}
          <div align ="right">
              <a class="ui red basic button" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove">Discard Comment</span></a>
              <a class="ui green basic button" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok">Approve Comment</span></a>
            </div>  
          {% endif %}
      {% endif %}
  {% empty %}
      <p>No comments posted.</p>
  {% endfor %}
</div>

{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
<div class="ui main text container">
      <div class="ui top  attached segment">
        <div class="ui huge header"> New Blog</div>

    <form method="POST" class="ui form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="ui violet basic button">Save</button>
    </form>
    </div>
    </div>
    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}


<div class="ui main text container">
    <div class="ui huge header">Blog App</div>
    <div class="ui top  attached segment">
        <div class="ui divided items">
          {% for post in post_list %}
            <div class="item">
              <div class="content">
                <a class="header" href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a>
                <div class="meta">
                  <span>Published on: {{ post.published_date|date:"D M Y"}}</span>
                </div>
                <div class="extra">
                  <a class="ui floated basic violet button" href="{% url 'blog:post_detail' pk=post.pk %}">
                    Comments: {{ post.approve_comments.count }}  <i class="right chevron icon"></i></a>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          </div>
          </div>

{% endblock %}

blog/templates/blog/registration.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="ui main text container">
      <div class="ui top  attached segment">
    <!--  {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
    -->
        <h1>Signup</h1>
        <h3>Please fill out the form.</h3>
        <form enctype="multipart/form-data" class="ui form" method="POST">
          {% csrf_token %}
          <!--{{ user_form.as_p }}
          {{ profile_form.as_p }}-->
            {% bootstrap_form user_form %}
            {% bootstrap_form profile_form %}
            <div class="btn" class="align-center">
              <input type="submit" class="ui basic button" name="" value="Submit">
          </div>
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}